### ISSUE TITLE
Add support for colored letters and background.

### ISSUE THREAD

**Issue by ivanmrsulja** [logicsquad/nanocaptcha#16]
All the constructors for content providers that take in color lists are deprecated. I think it would be benefitial is you added support for colored text/background.

**Comment by paulhoadley** [comment]
Hi Ivan,

Yeah, you're right, `DefaultWordRenderer(List<Color> colors, List<Font> fonts)` is deprecated, and `FastWordRenderer` doesn't offer a constructor taking `Color`s, nor does its `Builder` support adding `Color`s—it's just hard-wired to use `Color.BLACK`. This wasn't so much a war on `Color`s, though. The idea in both those classes was just to migrate usage to the `Builder` approach, and additionally in `FastWordRenderer` the emphasis was on removing choices and making everything simpler. We could certainly add `Color` choice back to either or both renderers.

**Comment by paulhoadley** [comment]
Added in #18.
