### ISSUE TITLE
Add salt and pepper noise

### ISSUE THREAD

**Issue by ivanmrsulja** [logicsquad/nanocaptcha#17]
I think it would be a good feature if you added [salt and pepper noise](https://en.wikipedia.org/wiki/Salt-and-pepper_noise) producer.

**Comment by paulhoadley** [comment]
Hi Ivan,

Good idea. Do you know of any open source implementations with a suitable license (compatible with our 3-clause BSD license)?

**Comment by paulhoadley** [comment]
Added in #19.
