### ISSUE TITLE
Problem reading font data inside a docker container

### ISSUE THREAD

**Issue by anthsup** [logicsquad/nanocaptcha#24]
I have no problems running the code using the library on my local machine, but when I try to run the code in the docker container, the following error occurs when captcha is generated:

```
[main] ERROR n.l.n.i.r.AbstractWordRenderer.fontFromResource Unable to load font '/fonts/CourierPrime-Bold.ttf'. 
java.io.IOException: Problem reading font data.
```

This happens two times (for both default fonts), and these cause another error:

```
[main] INFO  r.a.e.h.DefaultFallbackApiExceptionHandler.logInfo NullPointerException : Cannot invoke "java.awt.Font.createGlyphVector(java.awt.font.FontRenderContext, char[])" because "font" is null NullPointerException Cannot invoke "java.awt.Font.createGlyphVector(java.awt.font.FontRenderContext, char[])" because "font" is null
java.lang.NullPointerException: Cannot invoke "java.awt.Font.createGlyphVector(java.awt.font.FontRenderContext, char[])" because "font" is null
	at net.logicsquad.nanocaptcha.image.renderer.DefaultWordRenderer.render(DefaultWordRenderer.java:54)
```

My docker image is based on `bellsoft/liberica-openjdk-alpine:21` (I've tried Java 17, too). Nanocaptcha version is 2.1 (latest). I've also tried adding `fontconfig` and `ttf-dejavu` libs to the docker image but that didn't help.

Would appreciate any help on this, thanks!

**Comment by anthsup** [comment]
I've found out that when I use `bellsoft/liberica-openjdk-alpine-musl:21` as a base image and also install `ttf-dejavu` package everything works as expected.

It also works fine if I manually add `fontconfig.bfc` file to `/usr/lib/jvm/%YOUR_JAVA_VERSION%/lib` folder. Even with a basic alpine image and no additional packages installed.

I still don't quite understand why though..

**Comment by anthsup** [comment]
Well, I've googled and tested some more and what's finally worked for me even with `bellsoft/liberica-openjdk-alpine:21` image is adding `fontconfig.properties` file to `JAVA_HOME/lib` folder. After that there was no need to install any packages. So I'm closing the issue.

**Comment by paulhoadley** [comment]
Hi Anton,

Sorry—I didn't even get a chance to look at this before you closed it! I'm glad you sorted it out. I don't use Docker, so wouldn't have been able to add much.
