### ISSUE TITLE
Provide easy way to add other languages

### ISSUE THREAD

**Issue by FederationOfUnicorns** [logicsquad/nanocaptcha#7]
I am making good progress with my experiments and i stumbled upon another thing:
Currently, the library supports English and .wav files as sources. I am currently trying to add a few more languages.

How about providing an easy-to-use mechanism to add other languages (let's say by providing them in subfolders in a resources/nanocaptcha/samples   structure?

Might it be possible to use .mp3 files as well?

**Comment by paulhoadley** [comment]
> How about providing an easy-to-use mechanism to add other languages (let's say by providing them in subfolders in a resources/nanocaptcha/samples structure?

The _folder structure_ is already there: you'll see the English samples are in `src/main/resources/sounds/en/numbers`, where the `en` part corresponds to English. The audio part of the project remains pretty much a straight port from [SimpleCaptcha](https://sourceforge.net/p/simplecaptcha/), and I presume that's as far as localization support went in that project—I haven't made any significant changes. In any case, if you can supply the samples for the 0–9 digits in some other language, I'll look at adding support.

> Might it be possible to use .mp3 files as well?

Open another ticket for this, and we can look into it.

**Comment by FederationOfUnicorns** [comment]
Here are german wav samples (DE_A_x   and DE_B_x, two "voices")

[German Wav Digits.zip](https://github.com/logicsquad/nanocaptcha/files/9715640/German.Wav.Digits.zip)

**Comment by paulhoadley** [comment]
I am getting started on this. As part of this improvement, I am going to deprecate the `RandomNumberVoiceProducer(Map<Integer, List<String>>)` constructor: being able to add your own vocalisations is a nice idea, I suppose, but I think a better path here would be to add different languages to the project here, like @FederationOfUnicorns has done above.

**Comment by paulhoadley** [comment]
You can now create a CAPTCHA using the German samples. You can either explicitly add a `RandomNumberVoiceProducer` like this:

```
AudioCaptcha audioCaptcha = new AudioCaptcha.Builder().addContent().addVoice(new RandomNumberVoiceProducer(Locale.GERMAN)).build();
```

or set the system property `net.logicsquad.nanocaptcha.audio.producer.RandomNumberVoiceProducer.defaultLanguage` to `de` to make German the default, and then this will use the German samples:

```
AudioCaptcha audioCaptcha = new AudioCaptcha.Builder().addContent().build();
```

To see this, you'll need to clone the repo and build 1.4-SNAPSHOT yourself at the moment.

**Comment by paulhoadley** [comment]
In the absence of further discussion, I'm going to call this done.
