### ISSUE TITLE
Support MP3 as sound format

### ISSUE THREAD

**Issue by FederationOfUnicorns** [logicsquad/nanocaptcha#8]
It would be nice (and reduce library size) to support mp3 format as sound source.

[German MP3 Digits.zip](https://github.com/logicsquad/nanocaptcha/files/9715638/German.MP3.Digits.zip)

**Comment by paulhoadley** [comment]
This is a reasonable idea (those samples are significantly smaller), _but_ I don't think we're going to be able to support it without a third-party library, are we? One of the project goals is to be minimally dependent. If you can tell me how to do it without pulling in another library, by all means re-open this ticket.
