### ISSUE TITLE
Possible to define image captcha length in fluent

### ISSUE THREAD

**Issue by FederationOfUnicorns** [logicsquad/nanocaptcha#9]
Would it be possible to expand the default content producer to accept a numeric value as its content length?

like in this hypothetical example .. trying to get a 8 character captcha

ImageCaptcha imageCaptcha = new ImageCaptcha.Builder(200, 50).addContent(8).build();

**Comment by FederationOfUnicorns** [comment]
Although it might be confusing for the non-latin-content-producer use case

**Comment by paulhoadley** [comment]
`ImageCaptcha.Builder` and `AudioCaptcha.Builder` now both support `addContent(int)`.
